[theme]
# The primary color (This fixes the Blue buttons -> Red)
primaryColor = "#FF1801"

# Background color (Dark, matches your gradient feel)
backgroundColor = "#0E1117"

# Secondary background (This fixes the Black inputs -> Grey)
secondaryBackgroundColor = "#262730"

# Text color
textColor = "#FAFAFA"

# Font
font = "sans serif"
